export interface FilterOptions {
  levels: string[];
  geCategories: string[];
  departments: string[];
}

export interface StringifiedFilterOptions {
  stringifiedLevels: string;
  stringifiedGeCategories: string;
  stringifiedDepartments: string;
}

export const levels: Record<string, string> = {
  LowerDiv: 'Lower Division',
  UpperDiv: 'Upper Division',
  Graduate: 'Graduate',
};

export const geCategories: Record<string, string> = {
  'GE-1A': 'Lower Division Writing',
  'GE-1B': 'Upper Division Writing',
  'GE-2': 'Science and Technology',
  'GE-3': 'Social and Behavioral Sciences',
  'GE-4': 'Arts and Humanities',
  'GE-5A': 'Quantitative Literacy',
  'GE-5B': 'Formal Reasoning',
  'GE-6': 'Language Other Than English',
  'GE-7': 'Multicultural Studies',
  'GE-8': 'International/Global Issues',
};

export const departments: Record<string, string> = {
  'AC ENG': 'Academic English and ESL',
  AFAM: 'African American Studies',
  ANATOMY: 'Anatomy and Neurobiology',
  ANESTH: 'Anesthesiology',
  ANTHRO: 'Anthropology',
  ARABIC: 'Arabic',
  ARMN: 'Armenian',
  ART: 'Art',
  'ART HIS': 'Art History',
  ARTS: 'Arts',
  ARTSHUM: 'Arts and Humanities',
  ASIANAM: 'Asian American Studies',
  BANA: 'Business Analytics',
  BATS: 'Biomedical and Translational Science',
  'BIO SCI': 'Biological Sciences',
  BIOCHEM: 'Biological Chemistry',
  BME: 'Biomedical Engineering',
  CAMPREC: 'Campus Recreation',
  CBE: 'Chemical and Biomolecular Engineering',
  CEM: 'Community and Environmental Medicine',
  'CHC/LAT': 'Chicano Latino',
  CHEM: 'Chemistry',
  CHINESE: 'Chinese',
  CLASSIC: 'Classics',
  'CLT&THY': 'Culture & Theory',
  COGS: 'Cognitive Sciences',
  'COM LIT': 'Comparative Literature',
  COMPSCI: 'Computer Science',
  CRITISM: 'Criticism',
  'CRM/LAW': 'Criminology, Law and Society',
  CSE: 'Computer Science and Engineering',
  DANCE: 'Dance',
  DERM: 'Dermatology',
  'DEV BIO': 'Developmental and Cell Biology',
  DRAMA: 'Drama',
  EARTHSS: 'Earth System Science',
  EAS: 'East Asian Studies',
  'ECO EVO': 'Ecology and Evolutionary Biology',
  ECON: 'Economics',
  ECPS: 'Embedded and Cyber-Physical Systems',
  'ED AFF': 'Educational Affairs (Sch of Med)',
  EDUC: 'Education',
  EECS: 'Electrical Engineering & Computer Science',
  EHS: 'Environmental Health Sciences',
  ENGLISH: 'English',
  ENGR: 'Engineering',
  ENGRCEE: 'Engineering, Civil and Environmental',
  ENGRMAE: 'Engineering, Mechanical and Aerospace',
  EPIDEM: 'Epidemiology',
  'ER MED': 'Emergency Medicine',
  'EURO ST': 'European Studies',
  'FAM MED': 'Family Medicine',
  FIN: 'Finance',
  'FLM&MDA': 'Film and Media Studies',
  FRENCH: 'French',
  GDIM: 'Game Design and Interactive Media',
  'GEN&SEX': 'Gender and Sexuality Studies',
  GERMAN: 'German',
  'GLBL ME': 'Global Middle East Studies',
  GLBLCLT: 'Global Cultures',
  GREEK: 'Greek',
  HEBREW: 'Hebrew',
  HINDI: 'Hindi',
  HISTORY: 'History',
  HUMAN: 'Humanities',
  HUMARTS: 'Humanities and Arts',
  'I&C SCI': 'Information and Computer Science',
  IN4MATX: 'Informatics',
  INNO: 'Masters of Innovation and Entrepreneurship',
  'INT MED': 'Internal Medicine',
  'INTL ST': 'International Studies',
  IRAN: 'Iranian',
  ITALIAN: 'Italian',
  JAPANSE: 'Japanese',
  KOREAN: 'Korean',
  LATIN: 'Latin',
  LAW: 'Law',
  'LIT JRN': 'Literary Journalism',
  LPS: 'Logic and Philosophy of Science',
  LSCI: 'Language Science',
  'M&MG': 'Microbiology and Molecular Genetics',
  MATH: 'Mathematics',
  MED: 'Medicine',
  'MED ED': 'Medical Education',
  'MED HUM': 'Medical Humanities',
  MGMT: 'Management',
  'MGMT EP': 'Executive MBA',
  'MGMT FE': 'Fully Employed MBA',
  'MGMT HC': 'Health Care MBA',
  MGMTMBA: 'Management MBA',
  MGMTPHD: 'Management PhD',
  'MIC BIO': 'Microbiology',
  'MOL BIO': 'Molecular Biology and Biochemistry',
  MPAC: 'Accounting',
  MSE: 'Materials Science and Engineering',
  MUSIC: 'Music',
  'NET SYS': 'Networked Systems',
  NEURBIO: 'Neurobiology and Behavior',
  NEUROL: 'Neurology',
  'NUR SCI': 'Nursing Science',
  'OB/GYN': 'Obstetrics and Gynecology',
  OPHTHAL: 'Ophthalmology',
  PATH: 'Pathology and Laboratory Medicine',
  'PED GEN': 'Pediatrics Genetics',
  PEDS: 'Pediatrics',
  PERSIAN: 'Persian',
  PHARM: 'Medical Pharmacology',
  PHILOS: 'Philosophy',
  PHRMSCI: 'Pharmaceutical Sciences',
  'PHY SCI': 'Physical Science',
  PHYSICS: 'Physics',
  PHYSIO: 'Physiology and Biophysics',
  PLASTIC: 'Plastic Surgery',
  'PM&R': 'Physical Medicine and Rehabilitation',
  'POL SCI': 'Political Science',
  PORTUG: 'Portuguese',
  PSCI: 'Psychological Science',
  PSYCH: 'Psychology',
  'PUB POL': 'Public Policy',
  PUBHLTH: 'Public Health',
  RADIO: 'Radiology',
  'REL STD': 'Religious Studies',
  ROTC: "Reserve Officers' Training Corps",
  RUSSIAN: 'Russian',
  'SOC SCI': 'Social Science',
  SOCECOL: 'Social Ecology',
  SOCIOL: 'Sociology',
  SPANISH: 'Spanish',
  SPPS: 'Social Policy & Public Service',
  STATS: 'Statistics',
  SURGERY: 'Surgery',
  SWE: 'Software Engineering',
  TAGALOG: 'Tagalog',
  TOX: 'Toxicology',
  UCDC: 'UC Washington DC',
  'UNI AFF': 'University Affairs',
  'UNI STU': 'University Studies',
  UPPP: 'Urban Planning and Public Policy',
  VIETMSE: 'Vietnamese',
  'VIS STD': 'Visual Studies',
  WRITING: 'Writing',
};

export function stringifySearchFilters(filters: FilterOptions): StringifiedFilterOptions {
  return {
    stringifiedLevels: Object.entries(levels).find(([, label]) => label === filters.levels.join(','))?.[0] || '',
    stringifiedGeCategories:
      Object.entries(geCategories).find(([, label]) => label === filters.geCategories.join(','))?.[0] || '',
    stringifiedDepartments: filters.departments.length > 0 ? filters.departments.join(',') : '',
  } as StringifiedFilterOptions;
}
