name: Build and deploy PeterPortal
inputs:
  DATABASE_URL:
    description: Postgres database URL (different URLs for prod/dev)
    required: true
  NODE_ENV:
    description: Node environment, either "production" or "staging"
    required: true
  stage:
    description: Stage name, e.g. "prod" or "staging-123"
    required: true
runs:
  using: composite
  steps:
    - name: Build and deploy
      run: pnpm sst deploy --stage ${{ inputs.stage }}
      env:
        DATABASE_URL: ${{ inputs.DATABASE_URL }}
        NODE_ENV: ${{ inputs.NODE_ENV }}

        PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        GOOGLE_CLIENT: ${{ secrets.GOOGLE_CLIENT }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
        GRECAPTCHA_SECRET: ${{ secrets.GRECAPTCHA_SECRET }}
        ADMIN_EMAILS: ${{ secrets.ADMIN_EMAILS }}
        PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ANTEATER_API_KEY: ${{ secrets.ANTEATER_API_KEY }}
