service: peterportal-core
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${env:STAGING_PREFIX}peterportal.org
    certificateName: 'peterportal.org'
    createRoute53Record: true
    autoDomain: true

package:
  patterns:
    - '!src/**'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${env:STAGE_NAME}
  stackName: peterportal-core-${env:STAGE_NAME}
  apiGateway:
    binaryMediaTypes:
      - 'image/*'

functions:
  app:
    handler: dist/app.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY
