name: Clean up PR

on:
  pull_request:
    types: [closed]
    branches:
      - master

concurrency:
  group: deploy-${{ github.head_ref || github.run_id }}

jobs:
  clean-up-pr:
    runs-on: ubuntu-latest
    env:
      STAGING_PREFIX: staging-${{ github.event.pull_request.number }}.
      STAGE_NAME: staging-${{ github.event.pull_request.number }}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Dump Environment Variables
        run: |
          cd api && printf "STAGING_PREFIX=$STAGING_PREFIX\n \
            STAGE_NAME=$STAGE_NAME" > .env

      - name: Remove Serverless stack
        uses: serverless/github-action@v3.1
        with:
          args: >
            -c "cd api && 
            serverless plugin install --name serverless-dotenv-plugin && 
            serverless plugin install --name serverless-domain-manager && 
            serverless remove"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
