name: Clean up PR

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean-up-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        env:
          HUSKY: 0

      - name: Remove staging stack
        run: npx sst remove --stage staging-${{ github.event.pull_request.number }}
        env:
          CI: false
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deactivate deployment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          environment: staging-${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyDeactivateDeployments: true
