name: Clean up PR

on:
  pull_request:
    types: [closed]
    branches:
      - master

concurrency:
  group: deploy-${{ github.head_ref || github.run_id }}

jobs:
  clean-up-pr:
    runs-on: ubuntu-latest
    env:
      STAGING_PREFIX: staging-${{ github.event.pull_request.number }}.
      STAGE_NAME: staging-${{ github.event.pull_request.number }}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Remove staging stack
        run: npx sst remove --stage ${{ format('staging-{0}', github.event.pull_request.number) }} backend && npx sst remove --stage ${{ format('staging-{0}', github.event.pull_request.number) }} frontend
        env:
          CI: false
          PUBLIC_API_URL: ${{secrets.PUBLIC_API_URL}}
          PUBLIC_API_GRAPHQL_URL: ${{secrets.PUBLIC_API_GRAPHQL_URL}}
          MONGO_URL: ${{secrets.MONGO_URL}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
          GOOGLE_CLIENT: ${{secrets.GOOGLE_CLIENT}}
          GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
          GRECAPTCHA_SECRET: ${{secrets.GRECAPTCHA_SECRET}}
          ADMIN_EMAILS: ${{secrets.ADMIN_EMAILS}}
          PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
