name: Clean up PR

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  STAGE: staging-${{ github.event.pull_request.number }}

jobs:
  clean-up-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        env:
          HUSKY: 0

      - name: Remove staging stack
        run: npx sst remove --stage $STAGE backend && npx sst remove --stage $STAGE frontend
        env:
          CI: false
          PUBLIC_API_URL: ${{secrets.PUBLIC_API_URL}}
          PUBLIC_API_GRAPHQL_URL: ${{secrets.PUBLIC_API_GRAPHQL_URL}}
          MONGO_URL: ${{secrets.MONGO_URL}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
          GOOGLE_CLIENT: ${{secrets.GOOGLE_CLIENT}}
          GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
          GRECAPTCHA_SECRET: ${{secrets.GRECAPTCHA_SECRET}}
          ADMIN_EMAILS: ${{secrets.ADMIN_EMAILS}}
          PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deactivate deployment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          environment: $STAGE
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyDeactivateDeployments: true
